export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const CLEAR_ORDER_DETAILS = 'CLEAR_ORDER_DETAILS';
export const CLEAR_ORDER_ERROR = 'CLEAR_ORDER_ERROR';

export const USER_ORDERS_REQUEST = 'USER_ORDERS_REQUEST';
export const USER_ORDERS_SUCCESS = 'USER_ORDERS_SUCCESS';
export const USER_ORDERS_FAIL = 'USER_ORDERS_FAIL';
export const CLEAR_USER_ORDERS_DETAILS = 'CLEAR_ORDER_DETAILS';
export const CLEAR_USER_ORDERS_ERROR = 'CLEAR_ORDER_ERROR';
